### PR TITLE
More code style fixes.

### PR DESCRIPTION
**Pull request by darthsteven**

### CODE REVIEW

**Comment by darthsteven** [comment]
This branch actually bumps our PHP requirement to 5.4, so cheeky!

**Comment by darthsteven** [comment]
Lets do this against a 2.x version of this module, which allows us to do the PHP 5.4 jump (from 5.3)

**Comment by darthsteven** [comment]
Jenkins retest this please.

**Comment by darthsteven** [comment]
@amoebanath any chance you could take a look at these (mostly) boring changes please? :)

**Review by amoebanath — APPROVED** [review]

**Comment by anotherjames** [comment]
If the PHPCS is picking up things that require PHP 5.4, should we be using a differently-configured PHPCS?

**Comment by darthsteven** [comment]
> If the PHPCS is picking up things that require PHP 5.4, should we be using a differently-configured PHPCS?

I don't think so. I'm making a decision to use the `callable` type hint. We should have a type hint of some kind, and figured as _almost all_ of the projects that use this module are on PHP 5.+
We don't _have_ to do this, but hey PHP 5.3 is OLD.

**Comment by anotherjames** [comment]
OK, well at least the change is driven by an actual decision, rather than just being enforced by our code sniffer config. 🤷‍♂️

**Pull request merged**
